---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-docker-config
  namespace: cicd
spec:
  encryptedData:
    config.json: AgB/gzpeXqtIMzSfuh8bfbFYIJFAoGAK0IrROq6hZBACkji6o56FSlGVIfQeybbS3N/RxjcAI21mYLtW79oj6ag0El6IktWcw7lIU4yLmGN97qgrdbL6cuY5IzeAQeL8klXVNTmcei7gcfmXtZjELZxfZmdGNnxYrddDHeELSBERjzHuB9ZDBphrQ3TLyGqU3pOO1h3BTGTs9hWDl27MTKft+1MXMZBSSddzlLZoawZ31IN0TjXd80gwajBfBJm1q2n5RESLqqvA/tix90gttV/tKXYD6FSdSZ4dzOn48wKRGrze56i/a2dDEQvwGiclMbEQ8PxloPI70AkQHl1YDXN7crh9LdYR2Az6NUcd4pOCyQSBbkQPTbc0d6yfC2WNpOqj7rT0mMmABkSZvX+h287AKWoUXzlBFdOJg5NrqAeHgwTAIMIdp+D6f48nvhW3jkkGRAYUQilVU7r4EouqyxVjwWvR+/FYZ5caRMqAVSGiYxG3jS3Yn4x7CmwbnZedOjoXy26X7yhGkw5X3z68eqNy0KHmBC5svjgKWtf01KZvvw5d8jk1PQu4KGYZVVxTZIPIqRi697ytnUAqPndT4hfE23cJKkSAHJKntv/w8+uuMD0Cr4aOkFXsal9qrEckNaWv7eemLY2ebV82wrP/R5y5hwCtIrTwdGpy84Zr4YepG+UrllpQU68zJMnNRjMGYYdIhe1+6IjqZaqQ6LIturUO6/ofuxzqMZrmPlRBMCJolPusdUsZacM3V6/fZZ2fzzWIMrKYoNK2z+T0m4M3BZ/zCEBofotabl5mf5CGm1HjbX2OwVPJ9Kh/1yaTEnTM
  template:
    metadata:
      name: arc-docker-config
      namespace: cicd
