---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-docker-config
  namespace: cicd
spec:
  encryptedData:
    config.json: AgA2g0A+nwB5LqJwiKrF8CffOVRgA0pBFwGq7aWqZAPzpkN3LM5cLEzfblM6ODiRdcZtuGK0Iw1dtcp35MYzq3l3aIqIVruD/1Yi3fg0I8akMgH0DvdfPjU6+Hz9gkcNlqIQp7Zmga+YlgbU1RFfiHSjlWwZ9cLsMVxT7YAoCqmsPyXIKDqLJmTwdGFOnjlSZ9OX8P+Tozdmz7XcuGZtvfPLtOe5rPttdRVkh8SCWd3Hc7QZBVV3HeAmLcT7Y+Qe91iKFSibOU4Wj/Al1XHKSFmu0+D12zsIadNxhSacXjiiQcRIGxf5rHNluJmAdEocjxfFGgZBoUK87JRdiW5DecyQsmBfivjyCK8bJEtBqaxDbztwV570w8n6onlUDbuGkcjfQyuPjHU4NV2TmRGW27rN6LNHfxfRIqAEs5vTbgLkERyh69mYG0MS+rAuzPNfm4iJiuqpwnohrTezfghH33rGGZYeDgN/1mbtF8v5H2k9i5bmWT9fmfAMjXlrKQla7PhKhGlt2WYrz7FaVOU9kv11ZAKzwqC0ENxpX4Toy+/HGXnTAaKAiB2pjVLqmx3wah780+yfSqFSyfRBwyfUFDxnuSKPkjjVLCf3ruA35SCmmP997GIjW5jhulkEInORq7uafPSEhJmPv+FqpxdFrYDg5PgJIv0PJ3usXSpAhOHavDPfl3066Ooev9KxnkZvvO7uOI3GpDytReuYymv+h42T8zD0gwBiXqckpO4XLxBsJYFuvzU1BA6qCITq7B/5Vr1yiZr7vodCCBSFYKPl9ltB++jHreTEEL6XkEE2yoQDatZCpq5n5wNENwYPe3Vs1HhvJfLuxPHRyKQcAaVaLR21i3XU2oz37+OzjA==
  template:
    metadata:
      name: arc-docker-config
      namespace: cicd
