---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: arc-docker-config
  namespace: cicd
spec:
  encryptedData:
    config.json: AgBhy7V43f32pyAmP5u4PNThtm8JcAvE3kk5DYrasYlP/I8Oj9GpNM16ZG+1SwiEXGtJb9G5T3d+V6gJ7SZvpPMhyNgjaZaoWgaGrpwb7xkksZdbvdAJ9dTFwYzAKb+eIlak7zWCJs6ZgRhDrdvORS8o5DlXCQGN4gGjsmiyYkBrxBX6LzoUX0nyHtSL91jdFGFNbncmqeWW3QZ/JZKM/GY2V+1eaZrJXfQq2hCQC2+WoDHIZExWePr0YvsxCgF9I57KjjEmNa+WyQ7AHqe8ESXYdjHUuWAAd7YLbnTs1syNSODLMAcwbV+5qLeY6QMd2JQN3OEV5Tg+AyDKec5rlzuuEzExluRP0D8w/je78/dvVTwElwGQuj06ur6xjTRZLMMaV9MYqgQNMihKZjEwyvlPMDaABfmqsu7/BS3iMc0vk1irIK3k7l9eLqR8iiTVW4cgLulWdK9HhLksGEf422oK8LYxIs8TN5NnQzcNtzoN8QhEWGTCvgvOMAYahnWMhbvEdOxB3tDmWouQA3/ByQ0IsGa4CWtAtj4eXImoujxuEZNn3joN7IDQoKHYgqXtlq+tl/6gR93z4ZlsH5S7DXD/WKoTOE32cJYOhUNPmsltEDO9QT8EphxW20q5Sos55PP5fm8Y6Q3MGAjqhQ8Cxk+A/NJV24YAyqhMtQ6TdvZ+ESSBIc6GgZ4I4z2bTFLJrVE+1G6E90h3I6NQ50CbirvddOYvzBHR9ffX9pZg/GFWO3F3Qk0KwZy9iWcOAsF3MY4BVO3/byPGw5yZyAnYvrXjZ79iJD2aabAl5xs17TwT6GyOf5N/GUsmXNxUBaLEL6SKK+UH5CcrtjlxXGwrTwVISrrra5CKLjVBrQ==
  template:
    metadata:
      name: arc-docker-config
      namespace: cicd
