apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: storage-system
data:
  config.json: |
    [
      {
        "clusterID": "44f39056-b008-4f74-a218-9a95e02802b2", 
        "monitors": [
          "10.10.10.11:6789", 
          "10.10.10.12:6789", 
          "10.10.10.13:6789"
        ]
      }
    ]