tailscale-operator:
  # 1. Credentials
  # We leave these empty so the operator looks for the 'operator-oauth' secret
  oauth:
    clientId: ""
    clientSecret: ""

  # 2. Developer Access
  # This enables the specific "Kubernetes API" device in Tailscale
  apiServerProxyConfig:
    mode: "true"

  # 3. Cleanup
  operatorConfig:
    cleanup: true