apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-mgmt-internal
  namespace: rabbitmq-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-public
    # Uses capture groups instead of a raw snippet
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - rabbitmq.internal.tatahostit.com
    secretName: rabbitmq-mgmt-tls
  rules:
  - host: rabbitmq.internal.tatahostit.com
    http:
      paths:
      - path: /()(.*) # Captures the path to pass to rewrite-target
        pathType: ImplementationSpecific
        backend:
          service:
            name: rabbitmq-ha
            port:
              number: 15672