apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml:
    # cloudflared will authenticate via the token in the Deployment env
    # This config only controls hostname->service routing.
    ingress:
      # Wildcard traffic goes ONLY to the Public Nginx Controller
      - hostname: "*.tatahostit.com"
        service: https://ingress-nginx-controller-public.ingress-nginx.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      - service: http_status:404