apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    # cloudflared will authenticate via the token in the Deployment env
    # This config only controls hostname->service routing.
    ingress:
      - hostname: podinfo.tatahostit.com
        service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: grafana.tatahostit.com
        service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80

      # Catch-all is REQUIRED
      - service: http_status:404