apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    config.yaml: |
    originRequest:
      noTLSVerify: true
      http2Origin: true
    
    ingress:
      # tatahostit.com rules
      - hostname: "*.tatahostit.com"
        service: https://ingress-nginx-public-controller.ingress-nginx.svc.cluster.local:443
      - hostname: "tatahostit.com"
        service: https://ingress-nginx-public-controller.ingress-nginx.svc.cluster.local:443

      # NEW: openring.ai rules
      - hostname: "*.openring.ai"
        service: https://ingress-nginx-public-controller.ingress-nginx.svc.cluster.local:443
      - hostname: "openring.ai"
        service: https://ingress-nginx-public-controller.ingress-nginx.svc.cluster.local:443
      
      - service: http_status:404